services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: 1235
      POSTGRES_DB: movies_db
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

